### ISSUE TITLE
ZBX_RESP_REGEX for Zabbix 2.0

### ISSUE THREAD

**Issue by skinkie** [jbfavre/python-zabbix#2]
My installation of Zabbix 2.0.12 requires a different ZBX_RESP_REGEX

``` python
ZBX_RESP_REGEX = r'Processed (\d+) Failed (\d+) Total (\d+) Seconds spent (\d\.\d+)'
```

**Comment by josevh** [comment]
This is already implemented.

I am on Zabbix 2.4.4 and the required ZBX_RESP_REGEX is the old one.

```
ZBX_RESP_REGEX = r'processed: (\d+); failed: (\d+); total: (\d+); seconds spent: (\d\.\d+)'
```

I submitted pull request #7 to revert.

The doc for 2.4.4 says it should be like yours. 
( https://www.zabbix.com/documentation/2.4/manual/concepts/sender )

I am not sure why they vary.

**Comment by jbfavre** [comment]
I've to check against Zabbix 2.0, but for both 2.2 & 2.4, the right REGEXP is:
`ZBX_RESP_REGEX = r'processed: (\d+); failed: (\d+); total: (\d+); seconds spent: (\d\.\d+)'` (checked from network capture dump).

My guess is that it'll be the same, since sender protocol didn't changed AFAIK.
Anyway, moved to jbfavre/python-protobix#4
